RestOnInfo/Pages/Greeting.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestOnInfo.Services;

namespace RestOnInfo.Pages
{
    public class GreetingModel : PageModel
    {
        private IGreeter _greeter;

        public string currentGreeting { get; set; }

        public GreetingModel(IGreeter greeter)
        {
            _greeter = greeter;
        }
        public void OnGet(string name)
        {
            currentGreeting = $"{name}: {_greeter.GetMessageOfTheDay()}";
        }
    }
}

RestOnInfo/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestOnInfo.Models;
using RestOnInfo.Services;
using RestOnInfo.ViewModels.Home;

namespace RestOnInfo.Pages
{
    public class IndexModel : PageModel
    {
        private IRestaurantData _restaurantData;
        private IGreeter _greeter;

        public IEnumerable<Restaurant> restaurants { get; set; }

        public IndexModel(IRestaurantData restaurantData,
            IGreeter greeter)
        {
            _restaurantData = restaurantData;
            _greeter = greeter;
        }
        public void OnGet()
        {
            var model = new HomeIndexViewModel();
            model.Restaurants = _restaurantData.GetAll();
            model.CurrentMessage = _greeter.GetMessageOfTheDay();

            restaurants = model.Restaurants;
        }
    }
}

RestOnInfo/ViewComponents/LoginLogoutViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    public class LoginLogoutViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("Default");
        }
    }
}

RestOnInfo/Pages/Greeting.cshtml
@page "{name}"

@model GreetingModel

<div>@Model.currentGreeting</div>

RestOnInfo/Pages/Index.cshtml
@page
@model IndexModel

@{ 
    ViewBag.Title = "Home Page";
 }     

@foreach (var restaurant in Model.restaurants)
 {
    @Html.Partial("_Summary", restaurant)
 }


<div>
    <a class="btn btn-default" asp-action="Create">Add Restaurant</a>
</div>

RestOnInfo/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Cabin+Sketch:400,700|Sirin+Stencil" rel="stylesheet">
    <style>
        .display {
            position: relative;
            background: linear-gradient(#242222,transparent), url("https://images.unsplash.com/photo-1453831362806-3d5577f014a4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=9dd8da96be0724ab84e4147d428f6bba&auto=format&fit=crop&w=738&q=80");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }

        .navbar-brand {
            font-family: Sirin Stencil;
            font-weight: 400;
            font-size: 30px;
        }
    </style>
</head>
<body class="display">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/"><i class="fas fa-utensils"></i> RestOnInfo</a>
            </div>
            <div class="navbar-right">
                <!--<vc:login-logout></vc:login-logout>-->
                <!--<a class="btn btn-default" asp-controller="Account" asp-action="Login">Login</a>-->
                @if (User.Identity.IsAuthenticated)
                {
                    <!--<div>Hello, @User.Identity.Name</div>-->
                    <a class="btn btn-default" style="margin-right:15px; margin-top:8px" asp-controller="Account" asp-action="Logout">Logout</a>
                }
                else
                {
                    <a class="btn btn-default" style="margin-right:5px; margin-top:8px" asp-controller="Account" asp-action="Login">Login</a>
                }
            </div>
        </div>
    </nav>
    <br />
    <br />
    <br /> 
    <div style="margin-left:10px; font-family: Sirin Stencil; color:white">Welcome, @User.Identity.Name</div>
    <div class="container" style="margin-left:30%; width:50%">

        @RenderBody()
        <footer>
            @RenderSection("footer", required: false)
        </footer>
    </div>
    <environment>
        <script src="~/node_modules/jquery/dist/jquery.js"></script>
        <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/node_modules/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
</body>
</html>

RestOnInfo/Pages/_Summary.cshtml
@model Restaurant


<header>
    <style>
        .panel-heading {
            font-family: Sirin Stencil;
            font-weight: 400;
            font-size: 35px;
        }

        .panel-body {
            font-family: Sirin Stencil;
            font-weight: 400;
            font-size: 20px;
        }
    </style>
</header>

<section class="panel panel-default">
    <h3 class="panel-heading">@Model.Name</h3>
    <div class="panel-body">
        Cuisine: @Model.Cuisine
    </div>
    <div class="panel-footer">
        <a class="btn btn-default" asp-action="Details" asp-route-id="@Model.Id">More</a>
        <a class="btn btn-default" asp-page="/Restaurants/Edit" asp-route-id="@Model.Id">Edit</a>
    </div>
</section>